import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SD Negeri Margasari",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>

    <header className="z-50 fixed top-0 right-0 w-full p-4 shadow-md" style={{backgroundColor: '#E8F5FC'}}>
      <nav className="container mx-auto">
        <ul className="flex justify-center space-x-4">
          <li><Link href="/" className="text-blue-600 hover:text-blue-800">Home</Link></li>
          <li><Link href="/tentang-sekolah" className="text-blue-600 hover:text-blue-800">Tentang Sekolah</Link></li>
          <li><Link href="/prestasi" className="text-blue-600 hover:text-blue-800">Prestasi</Link></li>
          <li><Link href="/galeri-sekolah" className="text-blue-600 hover:text-blue-800">Galeri Sekolah</Link></li>
          {/*<li><Link href="/berita" className="text-blue-600 hover:text-blue-800">Berita</Link></li>*/}
        </ul>
      </nav>
    </header>

    {children}</body>
    </html>
  );
}
